[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "eagle_test_graphs"
version = "0.0.1" 
[tool.setuptools.package-dir]
eagle_test_graphs = "graphs"
