name: Validate graphs

on: [push, pull_request]

jobs:

  validate_graphs:
    name: Validate graphs
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install jsonschema

      - name: Validate graphs
        run: |
          cd tools
          find ../eagle_test_graphs/daliuge_tests -type f -name '*.graph' -print0 | xargs -0 -I {} python checkGraph.py {}
